#!/bin/bash
# User setup script.
# (C) Mark Blakeney, 2017.

PROG="$(basename $0)"
NAME=${PROG%-*}

BINDIR="/usr/bin"
DOCDIR="/usr/share/doc/$NAME"
CNFDIR="/etc"

usage() {
    echo "Usage:"
    echo "sudo $PROG install|uninstall"
    echo "(-d option sets DESTDIR for install/uninstall)"
    exit 1
}

# Process command line options
DESTDIR=""
while getopts d: c; do
    case $c in
    d) DESTDIR="$OPTARG";;
    \?) usage;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage
fi

cmd="$1"

if [ $cmd = "install" -o $cmd = "uninstall" ]; then
    DESTDIR=$(echo "$DESTDIR" | sed 's:/*$::')
    if [ -z "$DESTDIR" -a "$(id -un)" != "root" ]; then
	echo "Install or uninstall must be run as sudo/root."
	exit 1
    fi

    if [ $cmd = "install" ]; then
	install -CDv -m 755 -t $DESTDIR$BINDIR $NAME
	install -CDv -m 755 -t $DESTDIR$BINDIR $NAME-setup
	install -CDv -m 644 -t $DESTDIR$CNFDIR $NAME.conf
	install -CDv -m 644 -t $DESTDIR$DOCDIR README.md

	# Also install HTML file if markdown is available
	if hash markdown &>/dev/null; then
	    markdown -o $DESTDIR$DOCDIR/README.html README.md
	fi
    else
	rm -rfv $DESTDIR$BINDIR/$NAME
	rm -rfv $DESTDIR$CNFDIR/$NAME.conf
	rm -rfv $DESTDIR$DOCDIR
	rm -rfv $DESTDIR$BINDIR/$NAME-setup
    fi
else
    usage
fi

exit 0
