[build-system]
requires = ["setuptools>=61.0", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pacpush"
description = "Utility to push an Arch host's package and AUR caches to other hosts"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.8"
keywords = ["pacman", "pacserve"]
dynamic = ["version"]
dependencies = [
  "platformdirs",
  "argparse-from-file",
  "requests",
  "pyalpm",
]

[[project.authors]]
name = "Mark Blakeney"
email = "mark.blakeney@bullet-systems.net"

[project.urls]
Homepage = "https://github.com/bulletmark/pacpush"

[project.scripts]
pacpush = "pacpush:main"

[tool.setuptools_scm]
version_scheme = "post-release"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
ignore = ["SIM115", "SIM905", "BLE001", "PLW1510", "DTZ"]

# vim:se sw=2:
